from flask import Flask, request, jsonify, render_template
from flask_cors import CORS
import csv
import os
import sys

app = Flask(__name__)
CORS(app)

# Config
PATH = "all excels/"

# Ensure directories exist
os.makedirs(PATH, exist_ok=True)
os.makedirs("logs", exist_ok=True)


def read_config_file(filename):
    """Read a config file and return its variables as a dict"""
    config = {}
    filepath = f"config/{filename}"

    if not os.path.exists(filepath):
        return config

    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    exec_globals = {"__builtins__": __builtins__}
    exec(content, exec_globals)

    for key, value in exec_globals.items():
        if not key.startswith("_") and not callable(value):
            config[key] = value

    return config


def save_config_file(config_dict, filename):
    """Save config dict to file"""
    filepath = f"config/{filename}"

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("'''\nAuthor: Generated by UI\n'''\n\n")
        for key, value in config_dict.items():
            if isinstance(value, str):
                f.write(f'{key} = "{value}"\n')
            elif isinstance(value, list):
                f.write(f"{key} = {value}\n")
            else:
                f.write(f"{key} = {value}\n")


# Load configs
personals = read_config_file("personals.py")
search_mod = read_config_file("search.py")
secrets_mod = read_config_file("secrets.py")
settings_mod = read_config_file("settings.py")
questions_mod = read_config_file("questions.py")


@app.route("/")
def home():
    return render_template("index.html")


@app.route("/applied-jobs", methods=["GET"])
def get_applied_jobs():
    try:
        jobs = []
        csv_path = PATH + "all_applied_applications_history.csv"
        if not os.path.exists(csv_path):
            return jsonify([])

        with open(csv_path, "r", encoding="utf-8") as file:
            reader = csv.DictReader(file)
            for row in reader:
                jobs.append(
                    {
                        "Job_ID": row.get("Job ID", ""),
                        "Title": row.get("Title", ""),
                        "Company": row.get("Company", ""),
                        "Work_Location": row.get("Work Location", ""),
                        "Work_Style": row.get("Work Style", ""),
                        "Date_Applied": row.get("Date Applied", ""),
                        "Job_Link": row.get("Job Link", ""),
                        "External_Job_link": row.get("External Job link", ""),
                    }
                )
        return jsonify(jobs)
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/failed-jobs", methods=["GET"])
def get_failed_jobs():
    try:
        jobs = []
        csv_path = PATH + "all_failed_applications_history.csv"
        if not os.path.exists(csv_path):
            return jsonify([])

        with open(csv_path, "r", encoding="utf-8") as file:
            reader = csv.DictReader(file)
            for row in reader:
                jobs.append(
                    {
                        "Job_ID": row.get("Job ID", ""),
                        "Title": row.get("Title", ""),
                        "Company": row.get("Company", ""),
                        "Job_Link": row.get("Job Link", ""),
                    }
                )
        return jsonify(jobs)
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/config/personals", methods=["GET", "POST"])
def config_personals():
    global personals
    if request.method == "GET":
        return jsonify(personals)

    data = request.json
    personals.update(data)
    save_config_file(personals, "personals.py")
    return jsonify({"success": True})


@app.route("/config/search", methods=["GET", "POST"])
def config_search():
    global search_mod
    if request.method == "GET":
        return jsonify(search_mod)

    data = request.json
    # Ensure search_terms has at least one item
    if not data.get("search_terms") or len(data["search_terms"]) == 0:
        data["search_terms"] = ["Software Engineer"]

    search_mod.update(data)
    save_config_file(search_mod, "search.py")
    return jsonify({"success": True})


@app.route("/config/secrets", methods=["GET", "POST"])
def config_secrets():
    global secrets_mod
    if request.method == "GET":
        return jsonify(secrets_mod)

    data = request.json
    secrets_mod.update(data)
    save_config_file(secrets_mod, "secrets.py")
    return jsonify({"success": True})


@app.route("/config/settings", methods=["GET", "POST"])
def config_settings():
    global settings_mod
    if request.method == "GET":
        return jsonify(settings_mod)

    data = request.json
    settings_mod.update(data)
    save_config_file(settings_mod, "settings.py")
    return jsonify({"success": True})


@app.route("/config/questions", methods=["GET", "POST"])
def config_questions():
    global questions_mod
    if request.method == "GET":
        return jsonify(questions_mod)

    data = request.json
    questions_mod.update(data)
    save_config_file(questions_mod, "questions.py")
    return jsonify({"success": True})


# Bot control - these are placeholders since bot runs locally
@app.route("/bot/start", methods=["POST"])
def bot_start():
    return jsonify({"message": "Inicia el bot desde tu terminal: python runAiBot.py"})


@app.route("/bot/stop", methods=["POST"])
def bot_stop():
    return jsonify({"message": "Detén el bot con Ctrl+C en la terminal"})


@app.route("/bot/status", methods=["GET"])
def bot_status():
    return jsonify(
        {"running": False, "message": "Ejecuta python runAiBot.py para iniciar el bot"}
    )


@app.route("/bot/logs", methods=["GET"])
def bot_logs():
    return jsonify(
        {"logs": ["Logs solo disponibles cuando el bot se ejecuta localmente"]}
    )


if __name__ == "__main__":
    app.run(debug=True, port=5000)
