"""
Author: Generated by UI
"""

default_resume_path = "resumes/Jon Pecina cv english 2026.pdf"
years_of_experience = "10"
require_visa = "No"
website = ""
linkedIn = "https://www.linkedin.com/in/jpecina/"
us_citizenship = "Other"
desired_salary = 60000
current_ctc = 800000
notice_period = 30
linkedin_headline = "CFO | Finance & Digital Transformation | AI-Driven Financial Strategy | ERP Systems | Data & Process Optimization"
linkedin_summary = "Finance executive with 15+ years of international experience across Europe and Latin America."
cover_letter = """Dear Hiring Manager,

I am writing to express my interest in opportunities within your finance team. With over 15 years of international experience across Europe and Latin America, I have developed strong expertise in financial management, accounting, reporting, budgeting, and internal controls within diverse and dynamic environments.

Throughout my career, I have held senior finance positions, including CFO and Finance Manager roles, where I was responsible for overseeing accounting operations, financial reporting under IFRS, treasury management, compliance, and audit coordination. I combine strategic financial insight with a hands-on approach, ensuring both accuracy in execution and alignment with business objectives.

I have extensive experience working with ERP systems, improving financial processes, strengthening internal controls, and supporting executive decision-making. My international background has allowed me to adapt quickly to different regulatory frameworks and multicultural teams, maintaining high standards of professionalism and accountability.

I am particularly motivated by roles where finance acts as a strategic partner to the business, contributing to operational efficiency, sustainable growth, and sound governance.

I would welcome the opportunity to discuss how my experience and commitment to excellence can add value to your organization.

Thank you for your time and consideration.

Kind regards,
Jon Peciña"""
user_information_all = ""
recent_employer = "Not Applicable"
confidence_level = "8"
pause_before_submit = False
pause_at_failed_question = False
overwrite_previous_answers = False
follow_previous_answers = True
