'''
Author: Generated by UI
'''

default_resume_path = "./resumes/Jon Pecina cv english 2026.pdf"
years_of_experience = "10"
require_visa = "No"
website = ""
linkedIn = "https://www.linkedin.com/in/jpecina/"
us_citizenship = "Other"
desired_salary = 60000
current_ctc = 800000
notice_period = 30
linkedin_headline = "CFO | Finance & Digital Transformation | AI-Driven Financial Strategy | ERP Systems | Data & Process Optimization"
linkedin_summary = "Finance executive with 15+ years of international experience across Europe and Latin America. Proven track record in financial leadership, budgeting, reporting, internal controls, and strategic decision support. Experienced in high-growth and multicultural environments, combining strong IFRS knowledge with a hands-on, analytical mindset. Adaptable, results-driven, and focused on building robust financial structures that enable sustainable growth."
cover_letter = "Dear Hiring Manager,

I am a finance professional with over 15 years of international experience across Europe and Latin America, covering financial reporting, budgeting, accounting operations, and internal controls. I have held senior finance roles, including CFO and Finance Manager positions, combining strategic oversight with hands-on execution.

My background includes IFRS reporting, financial planning, ERP management, audit coordination, and process optimization within multicultural and fast-paced environments. I am comfortable working both independently and as part of cross-functional teams, always with a strong focus on accuracy, compliance, and value creation.

I am motivated by roles where finance contributes not only to reporting, but to informed decision-making and sustainable growth.

I would welcome the opportunity to contribute my experience and international perspective to your organization.

Kind regards,
Jon Peciña"
user_information_all = ""
recent_employer = "Not Applicable"
confidence_level = "8"
pause_before_submit = False
pause_at_failed_question = True
overwrite_previous_answers = False
follow_previous_answers = True
