'''
Author:     Generated by UI

Copyright (C) 2024
'''

about_company_bad_words = []
about_company_good_words = []
bad_words = []
benefits = []
commitments = []
companies = []
current_experience = 10
date_posted = "Past 24 hours"
did_masters = True
easy_apply_only = True
english_only_jobs = True
experience_level = []
fair_chance_employer = False
in_your_network = False
industry = []
job_function = []
job_titles = []
job_type = []
location = []
on_site = ['On-site', 'Hybrid']
pause_after_filters = False
randomize_search_order = False
salary = ""
search_location = "EMEA"
search_terms = ['spanish']
security_clearance = False
sort_by = ""
switch_number = 30
under_10_applicants = True
